[package]
name = "ask"
version = "0.2.0"
edition = "2024"

[dependencies]
tokio = "1.49.0"
gh_models = "0.2.0"
clap = { version = "4", features = ["derive"]  }
colorline = "0.2.0"
cliux = "0.5.1"
crossterm = "0.29.0"
